### ISSUE TITLE
deprecated client_id option?

### ISSUE THREAD

**Issue by rockpapergoat** [treydock/puppet-module-globus#37]
it's entirely possible i'm doing this wrong, but using this module to install and configure globus 5, the exec that runs `globus-node-setup` fails with

```
Notice: /Stage[main]/Globus::Config/Exec[globus-endpoint-setup]/returns: Error: The --client-id option has been removed, see the 'endpoint key convert' command to update your deployment key and rerun this command without this option.
```

i did specify the client_id via hiera. the globus version installed is 5.4.67. does the module need an update to accommodate this change, or did i miss some option to avoid the issue?

**Comment by rockpapergoat** [comment]
sorry, it looks like setting `globus::run_setup_commands: false` does avoid this issue, but if someone does want to run the commands for some reason, the `--client-id` option will still cause an error.

**Comment by treydock** [comment]
Locally we never let Puppet run the setup commands since we've migrated from v4 to v5.3 to v5.4 and always did some of this manually.  I think there are also some flags missing for project-id and project-admin.  I'll get a PR together to only support 5.4.61+ of Globus.
